module.exports = {
    block: 'div',
    page: 'div',
    view: 'div',
    'scroll-view': 'div',
    swiper: 'div',
    'swiper-item': 'div',
    'movable-view': 'div',
    icon: 'i',
    text: 'span',
    progress: 'div',
    button: 'button',
    form: 'form',
    input: 'input',
    label: 'label',
    picker: 'div',
    'picker-view': 'div',
    slider: 'div',
    textarea: 'textarea',
    audio: 'object',
    image: 'img',
    video: 'object',
    map: 'div',
    canvas: 'canvas',
    'contact-button': 'button'
}